### ISSUE TITLE
Encrypt the passwords in the database

### ISSUE THREAD

**Issue by Kunwark** [TalhaAhmedAI/php_login_app#1]
The passwords can be extracted from the database if there is a security breach. 
![image](https://user-images.githubusercontent.com/13748763/121391243-00c61b00-c903-11eb-9fd5-a3c8e49b95ed.png)

We need to introduce some security here.  Its a good practice to hash passwords. 

To do: 
Make use of the password_hash() function to encrypt the passwords and then use password_hash() to verify the password provided by the user.

**Comment by TalhaAhmedAI** [comment]
Hi,

Passwords have been encrypted using password_hash(). I'm closing this issue now.
