### ISSUE TITLE
Move classes into a class folder 

### ISSUE THREAD

**Issue by Kunwark** [TalhaAhmedAI/php_login_app#2]
Right now classes and all other PHP files lie in the same directory. It's a good practice to keep all the classes in one class folder.  This helps to distinguish between classes and other files. It also helps to autoload them later on. It's always a good idea to organize the code.

**Comment by TalhaAhmedAI** [comment]
Hi, Kunwark!

Classes have been moved to a separate folder. So I'm marking this as resolved and closing the issue.

**Comment by Kunwark** [comment]
Is there a reason that you used a capital C with the folder name? I would recommend using a small letter to avoid case sensitivity issues when using dynamic paths.

**Comment by TalhaAhmedAI** [comment]
As per said classes folder has been renamed with all letters in lower case. I'm closing this issue now.
