### ISSUE TITLE
Make use of object properties instead of arguments to function

### ISSUE THREAD

**Issue by Kunwark** [TalhaAhmedAI/php_login_app#3]
In the user class, the register method uses arguments instead of class properties. We need to fix this approach because it gets hard to maintain when the number of columns starts increasing. Imagine having a table that has maybe 25-26 columns, how hard would it be to maintain such a function. Plus, every time you change a column's name, you will have to change it into so many different areas.  

So it's better to have a function that looks like the following code

`
public function register(){       
 $query    = "INSERT INTO users (username, email, password) 
VALUES ('$this->username','$this->email', '$this->password')";
// some more code
}
`

Similarly, the class definition would also change and it will start looking something like 

`

class User extends DbConnection{	
public $username; 
public $email;
...... 
public function register(){      
....
}
}

`

When assigning values use something like 
`
$user = new User;

$user->username = "New name";
....

`

**Comment by TalhaAhmedAI** [comment]
I'm closing this issue as I've taken care of it in the latest version.
