### ISSUE TITLE
Use a common header and footer 

### ISSUE THREAD

**Issue by Kunwark** [TalhaAhmedAI/php_login_app#4]
Good architecture is important for the application. Imagine you have to make one small change to the footer or the header, you will need to change the header on all the pages of the website. This is easy till you have limited pages but Imagine you have a site that has pages in hundreds, what happens then? 

So to avoid this problem, one solution is to have a common header that you can just include on all your pages. As part of this ticket, you are required to remove the header from all the pages and include it as a file. I would suggest keeping all the layout files in a layout folder as well.

**Comment by TalhaAhmedAI** [comment]
Hi,

As per your request header has been moved to a separate layout folder. So I'm closing this issue now.
